package com.vindasoft.order;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;

// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
// 排除了数据源自动配置，因为我们要自定义数据源的配置
@SpringBootApplication(exclude = { DataSourceAutoConfiguration.class })
public class OrderServerPlatformApplication {

    public static void main(String[] args) {
        SpringApplication.run(OrderServerPlatformApplication.class, args);
    }

}
